# minimal builtins stub
# TODO use full typeshed

from typing import Any, Callable, Iterable, Iterator, Sequence, TypeVar, overload

_T = TypeVar("_T")
_T_co = TypeVar("_T_co", covariant=True)
_KT = TypeVar("_KT")
_VT = TypeVar("_VT")

class object:
    def __init__(self) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class type:
    def __init__(self, o: object) -> None: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

class int:
    def __init__(self, x: str | bytes | int = ..., base: int = ...) -> None: ...
    def __add__(self, other: int) -> int: ...
    def __sub__(self, other: int) -> int: ...
    def __mul__(self, other: int) -> int: ...
    def __truediv__(self, other: int) -> float: ...
    def __floordiv__(self, other: int) -> int: ...
    def __mod__(self, other: int) -> int: ...
    def __pow__(self, other: int) -> int: ...
    def __neg__(self) -> int: ...
    def __pos__(self) -> int: ...
    def __abs__(self) -> int: ...
    def __lt__(self, other: int) -> bool: ...
    def __le__(self, other: int) -> bool: ...
    def __gt__(self, other: int) -> bool: ...
    def __ge__(self, other: int) -> bool: ...

class float:
    def __init__(self, x: str | bytes | float | int = ...) -> None: ...
    def __add__(self, other: float) -> float: ...
    def __sub__(self, other: float) -> float: ...
    def __mul__(self, other: float) -> float: ...
    def __truediv__(self, other: float) -> float: ...
    def __neg__(self) -> float: ...
    def __pos__(self) -> float: ...
    def __abs__(self) -> float: ...

class str:
    def __init__(self, object: object = ...) -> None: ...
    def __add__(self, other: str) -> str: ...
    def __mul__(self, n: int) -> str: ...
    def __contains__(self, item: str) -> bool: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, key: int | slice) -> str: ...
    def capitalize(self) -> str: ...
    def casefold(self) -> str: ...
    def center(self, width: int, fillchar: str = ...) -> str: ...
    def count(self, sub: str, start: int = ..., end: int = ...) -> int: ...
    def encode(self, encoding: str = ..., errors: str = ...) -> bytes: ...
    def endswith(self, suffix: str | tuple[str, ...], start: int = ..., end: int = ...) -> bool: ...
    def find(self, sub: str, start: int = ..., end: int = ...) -> int: ...
    def format(self, *args: Any, **kwargs: Any) -> str: ...
    def index(self, sub: str, start: int = ..., end: int = ...) -> int: ...
    def isalnum(self) -> bool: ...
    def isalpha(self) -> bool: ...
    def isascii(self) -> bool: ...
    def isdecimal(self) -> bool: ...
    def isdigit(self) -> bool: ...
    def isidentifier(self) -> bool: ...
    def islower(self) -> bool: ...
    def isnumeric(self) -> bool: ...
    def isprintable(self) -> bool: ...
    def isspace(self) -> bool: ...
    def istitle(self) -> bool: ...
    def isupper(self) -> bool: ...
    def join(self, iterable: Iterable[str]) -> str: ...
    def ljust(self, width: int, fillchar: str = ...) -> str: ...
    def lower(self) -> str: ...
    def lstrip(self, chars: str = ...) -> str: ...
    def partition(self, sep: str) -> tuple[str, str, str]: ...
    def replace(self, old: str, new: str, count: int = ...) -> str: ...
    def rfind(self, sub: str, start: int = ..., end: int = ...) -> int: ...
    def rindex(self, sub: str, start: int = ..., end: int = ...) -> int: ...
    def rjust(self, width: int, fillchar: str = ...) -> str: ...
    def rpartition(self, sep: str) -> tuple[str, str, str]: ...
    def rsplit(self, sep: str = ..., maxsplit: int = ...) -> list[str]: ...
    def rstrip(self, chars: str = ...) -> str: ...
    def split(self, sep: str = ..., maxsplit: int = ...) -> list[str]: ...
    def splitlines(self, keepends: bool = ...) -> list[str]: ...
    def startswith(self, prefix: str | tuple[str, ...], start: int = ..., end: int = ...) -> bool: ...
    def strip(self, chars: str = ...) -> str: ...
    def swapcase(self) -> str: ...
    def title(self) -> str: ...
    def upper(self) -> str: ...
    def zfill(self, width: int) -> str: ...

class bytes:
    def __init__(self, source: Iterable[int] | int | str = ..., encoding: str = ..., errors: str = ...) -> None: ...
    def decode(self, encoding: str = ..., errors: str = ...) -> str: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[int]: ...

class bool(int):
    def __init__(self, x: object = ...) -> None: ...
    def __and__(self, other: bool) -> bool: ...
    def __or__(self, other: bool) -> bool: ...
    def __xor__(self, other: bool) -> bool: ...

class list(Sequence[_T]):
    def __init__(self, iterable: Iterable[_T] = ...) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[_T]: ...
    def __getitem__(self, index: int) -> _T: ...
    def __setitem__(self, index: int, value: _T) -> None: ...
    def __delitem__(self, index: int) -> None: ...
    def __contains__(self, item: object) -> bool: ...
    def append(self, item: _T) -> None: ...
    def clear(self) -> None: ...
    def copy(self) -> list[_T]: ...
    def count(self, item: _T) -> int: ...
    def extend(self, iterable: Iterable[_T]) -> None: ...
    def index(self, item: _T, start: int = ..., stop: int = ...) -> int: ...
    def insert(self, index: int, item: _T) -> None: ...
    def pop(self, index: int = ...) -> _T: ...
    def remove(self, item: _T) -> None: ...
    def reverse(self) -> None: ...
    def sort(self, *, key: Callable[[_T], Any] = ..., reverse: bool = ...) -> None: ...

class dict(Sequence[_KT]):
    def __init__(self, **kwargs: _VT) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[_KT]: ...
    def __getitem__(self, key: _KT) -> _VT: ...
    def __setitem__(self, key: _KT, value: _VT) -> None: ...
    def __delitem__(self, key: _KT) -> None: ...
    def __contains__(self, key: object) -> bool: ...
    def clear(self) -> None: ...
    def copy(self) -> dict[_KT, _VT]: ...
    def get(self, key: _KT, default: _VT = ...) -> _VT: ...
    def items(self) -> Iterable[tuple[_KT, _VT]]: ...
    def keys(self) -> Iterable[_KT]: ...
    def pop(self, key: _KT, default: _VT = ...) -> _VT: ...
    def popitem(self) -> tuple[_KT, _VT]: ...
    def setdefault(self, key: _KT, default: _VT = ...) -> _VT: ...
    def update(self, other: dict[_KT, _VT] = ..., **kwargs: _VT) -> None: ...
    def values(self) -> Iterable[_VT]: ...

class set(Sequence[_T]):
    def __init__(self, iterable: Iterable[_T] = ...) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[_T]: ...
    def __contains__(self, item: object) -> bool: ...
    def add(self, item: _T) -> None: ...
    def clear(self) -> None: ...
    def copy(self) -> set[_T]: ...
    def discard(self, item: _T) -> None: ...
    def pop(self) -> _T: ...
    def remove(self, item: _T) -> None: ...

class tuple(Sequence[_T_co]):
    def __init__(self, iterable: Iterable[_T_co] = ...) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[_T_co]: ...
    def __getitem__(self, index: int) -> _T_co: ...
    def __contains__(self, item: object) -> bool: ...
    def count(self, item: Any) -> int: ...
    def index(self, item: Any, start: int = ..., stop: int = ...) -> int: ...

class range(Sequence[int]):
    @overload
    def __init__(self, stop: int) -> None: ...
    @overload
    def __init__(self, start: int, stop: int, step: int = ...) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[int]: ...
    def __getitem__(self, index: int) -> int: ...
    def __contains__(self, item: object) -> bool: ...

# Built-in functions
def abs(x: int) -> int: ...
def all(iterable: Iterable[object]) -> bool: ...
def any(iterable: Iterable[object]) -> bool: ...
def ascii(obj: object) -> str: ...
def bin(x: int) -> str: ...
def callable(obj: object) -> bool: ...
def chr(i: int) -> str: ...
def dir(obj: object = ...) -> list[str]: ...
def divmod(x: int, y: int) -> tuple[int, int]: ...
def enumerate(iterable: Iterable[_T], start: int = ...) -> Iterator[tuple[int, _T]]: ...
def filter(function: Callable[[_T], bool] | None, iterable: Iterable[_T]) -> Iterator[_T]: ...
def format(value: object, format_spec: str = ...) -> str: ...
def getattr(obj: object, name: str, default: Any = ...) -> Any: ...
def globals() -> dict[str, Any]: ...
def hasattr(obj: object, name: str) -> bool: ...
def hash(obj: object) -> int: ...
def hex(x: int) -> str: ...
def id(obj: object) -> int: ...
def input(prompt: str = ...) -> str: ...
def isinstance(obj: object, classinfo: type | tuple[type, ...]) -> bool: ...
def issubclass(cls: type, classinfo: type | tuple[type, ...]) -> bool: ...
def iter(obj: Iterable[_T]) -> Iterator[_T]: ...
def len(obj: Sequence[Any]) -> int: ...
def locals() -> dict[str, Any]: ...
def map(func: Callable[..., _T], *iterables: Iterable[Any]) -> Iterator[_T]: ...
def max(iterable: Iterable[_T], *, key: Callable[[_T], Any] = ..., default: _T = ...) -> _T: ...
def min(iterable: Iterable[_T], *, key: Callable[[_T], Any] = ..., default: _T = ...) -> _T: ...
def next(iterator: Iterator[_T], default: _T = ...) -> _T: ...
def oct(x: int) -> str: ...
def open(file: str, mode: str = ..., buffering: int = ..., encoding: str = ..., errors: str = ..., newline: str = ..., closefd: bool = ..., opener: Callable[[str, int], int] = ...) -> Any: ...
def ord(c: str) -> int: ...
def pow(base: int, exp: int, mod: int = ...) -> int: ...
def print(*values: object, sep: str = ..., end: str = ..., file: Any = ..., flush: bool = ...) -> None: ...
def repr(obj: object) -> str: ...
def reversed(seq: Sequence[_T]) -> Iterator[_T]: ...
def round(number: float, ndigits: int = ...) -> float: ...
def setattr(obj: object, name: str, value: Any) -> None: ...
def sorted(iterable: Iterable[_T], *, key: Callable[[_T], Any] = ..., reverse: bool = ...) -> list[_T]: ...
def sum(iterable: Iterable[_T], start: _T = ...) -> _T: ...
def vars(obj: object = ...) -> dict[str, Any]: ...
def zip(*iterables: Iterable[Any]) -> Iterator[tuple[Any, ...]]: ...

# Exceptions
class BaseException:
    args: tuple[Any, ...]
    def __init__(self, *args: object) -> None: ...
    def __str__(self) -> str: ...

class Exception(BaseException): ...
class TypeError(Exception): ...
class ValueError(Exception): ...
class KeyError(Exception): ...
class IndexError(Exception): ...
class AttributeError(Exception): ...
class NameError(Exception): ...
class RuntimeError(Exception): ...
class StopIteration(Exception): ...
class ImportError(Exception): ...
class OSError(Exception): ...
class FileNotFoundError(OSError): ...
class IOError(OSError): ...
class ZeroDivisionError(Exception): ...
class AssertionError(Exception): ...
class NotImplementedError(Exception): ...
class SyntaxError(Exception): ...
class IndentationError(SyntaxError): ...
class TabError(IndentationError): ...
class MemoryError(Exception): ...
class RecursionError(RuntimeError): ...
class KeyboardInterrupt(BaseException): ...
class SystemExit(BaseException): ...
