from typing import Any, Iterator, Sequence

name: str
sep: str
linesep: str
curdir: str
pardir: str
extsep: str
altsep: str | None
pathsep: str
devnull: str

class PathLike:
    def __fspath__(self) -> str: ...

def getcwd() -> str: ...
def chdir(path: str | PathLike) -> None: ...
def listdir(path: str | PathLike = ...) -> list[str]: ...
def mkdir(path: str | PathLike, mode: int = ...) -> None: ...
def makedirs(name: str | PathLike, mode: int = ..., exist_ok: bool = ...) -> None: ...
def remove(path: str | PathLike) -> None: ...
def rmdir(path: str | PathLike) -> None: ...
def rename(src: str | PathLike, dst: str | PathLike) -> None: ...
def stat(path: str | PathLike) -> Any: ...
def walk(top: str | PathLike, topdown: bool = ..., onerror: Any = ..., followlinks: bool = ...) -> Iterator[tuple[str, list[str], list[str]]]: ...
def getenv(key: str, default: str = ...) -> str | None: ...
def environ() -> dict[str, str]: ...

class path:
    @staticmethod
    def exists(path: str | PathLike) -> bool: ...
    @staticmethod
    def isfile(path: str | PathLike) -> bool: ...
    @staticmethod
    def isdir(path: str | PathLike) -> bool: ...
    @staticmethod
    def join(path: str, *paths: str) -> str: ...
    @staticmethod
    def basename(path: str) -> str: ...
    @staticmethod
    def dirname(path: str) -> str: ...
    @staticmethod
    def split(path: str) -> tuple[str, str]: ...
    @staticmethod
    def splitext(path: str) -> tuple[str, str]: ...
    @staticmethod
    def abspath(path: str) -> str: ...
    @staticmethod
    def realpath(path: str) -> str: ...
    @staticmethod
    def expanduser(path: str) -> str: ...
    @staticmethod
    def expandvars(path: str) -> str: ...
