[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2024"
rust-version = "1.85"
license = "MIT"
repository = "https://github.com/pradoz/sneklsp"

[workspace.dependencies]
sneklsp_text = { path = "crates/sneklsp_text" }
sneklsp_lexer = { path = "crates/sneklsp_lexer" }
sneklsp_ast = { path = "crates/sneklsp_ast" }
sneklsp_parser = { path = "crates/sneklsp_parser" }

anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
compact_str = "0.9"
thiserror = "2.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

insta = "1.42"

bumpalo = "3.16"
dhat = "0.3"
criterion = { version = "0.5", features = ["html_reports"] }

[workspace.lints.rust]
unsafe_code = "warn"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -2 }
module_name_repetitions = "allow"
must_use_candidate = "allow"

[profile.release]
lto = "fat"
codegen-units = 1
