use lsp_types::CompletionItemKind;

pub struct BuiltinInfo {
    pub name: &'static str,
    pub kind: CompletionItemKind,
    pub detail: &'static str,
    pub signature: &'static str,
    pub doc: &'static str,
}

pub fn lookup(name: &str) -> Option<&'static BuiltinInfo> {
    BUILTINS.iter().find(|b| b.name == name)
}

pub static BUILTINS: &[BuiltinInfo] = &[
    BuiltinInfo {
        name: "abs",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "abs(x, /)",
        doc: "Return the absolute value of the argument.",
    },
    BuiltinInfo {
        name: "all",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "all(iterable, /)",
        doc: "Return True if bool(x) is True for all values x in the iterable.\n\nIf the iterable is empty, return True.",
    },
    BuiltinInfo {
        name: "any",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "any(iterable, /)",
        doc: "Return True if bool(x) is True for any x in the iterable.\n\nIf the iterable is empty, return False.",
    },
    BuiltinInfo {
        name: "ascii",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "ascii(obj, /)",
        doc: "Return an ASCII-only representation of an object.",
    },
    BuiltinInfo {
        name: "bin",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "bin(number, /)",
        doc: "Return the binary representation of an integer.",
    },
    BuiltinInfo {
        name: "bool",
        kind: CompletionItemKind::CLASS,
        detail: "builtin",
        signature: "class bool(x=False)",
        doc: "Returns True when the argument x is true, False otherwise.",
    },
    BuiltinInfo {
        name: "breakpoint",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "breakpoint(*args, **kws)",
        doc: "Call sys.breakpointhook(*args, **kws).",
    },
    BuiltinInfo {
        name: "bytearray",
        kind: CompletionItemKind::CLASS,
        detail: "builtin",
        signature: "class bytearray(source=b'', encoding='utf-8', errors='strict')",
        doc: "Mutable sequence of bytes.",
    },
    BuiltinInfo {
        name: "bytes",
        kind: CompletionItemKind::CLASS,
        detail: "builtin",
        signature: "class bytes(source=b'', encoding='utf-8', errors='strict')",
        doc: "Immutable sequence of bytes.",
    },
    BuiltinInfo {
        name: "callable",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "callable(obj, /)",
        doc: "Return whether the object is callable.",
    },
    BuiltinInfo {
        name: "chr",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "chr(i, /)",
        doc: "Return a Unicode string of one character with ordinal i.",
    },
    BuiltinInfo {
        name: "classmethod",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "classmethod(function)",
        doc: "Convert a function to be a class method.",
    },
    BuiltinInfo {
        name: "compile",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "compile(source, filename, mode, flags=0, dont_inherit=False, optimize=-1)",
        doc: "Compile source into a code object that can be executed by exec() or eval().",
    },
    BuiltinInfo {
        name: "complex",
        kind: CompletionItemKind::CLASS,
        detail: "builtin",
        signature: "class complex(real=0, imag=0)",
        doc: "Create a complex number from a real part and an optional imaginary part.",
    },
    BuiltinInfo {
        name: "delattr",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "delattr(obj, name, /)",
        doc: "Deletes the named attribute from the given object.",
    },
    BuiltinInfo {
        name: "dict",
        kind: CompletionItemKind::CLASS,
        detail: "builtin",
        signature: "class dict(**kwargs)",
        doc: "Dictionary object.",
    },
    BuiltinInfo {
        name: "dir",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "dir(object=None)",
        doc: "If called without an argument, return the names in the current scope. Otherwise, return an alphabetized list of names comprising some of the attributes of the given object.",
    },
    BuiltinInfo {
        name: "divmod",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "divmod(a, b, /)",
        doc: "Return the tuple (a//b, a%b).",
    },
    BuiltinInfo {
        name: "enumerate",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "enumerate(iterable, start=0)",
        doc: "Return an enumerate object.",
    },
    BuiltinInfo {
        name: "eval",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "eval(expression, globals=None, locals=None)",
        doc: "Evaluate the given source in the context of globals and locals.",
    },
    BuiltinInfo {
        name: "exec",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "exec(object, globals=None, locals=None)",
        doc: "Execute the given source in the context of globals and locals.",
    },
    BuiltinInfo {
        name: "filter",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "filter(function, iterable)",
        doc: "Construct an iterator from those elements of iterable for which function is true.",
    },
    BuiltinInfo {
        name: "float",
        kind: CompletionItemKind::CLASS,
        detail: "builtin",
        signature: "class float(x=0.0)",
        doc: "Convert a string or number to a floating point number.",
    },
    BuiltinInfo {
        name: "format",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "format(value, format_spec='')",
        doc: "Return value.__format__(format_spec).",
    },
    BuiltinInfo {
        name: "frozenset",
        kind: CompletionItemKind::CLASS,
        detail: "builtin",
        signature: "class frozenset(iterable=())",
        doc: "Build an immutable unordered collection of unique elements.",
    },
    BuiltinInfo {
        name: "getattr",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "getattr(object, name, default=...)",
        doc: "Get a named attribute from an object.",
    },
    BuiltinInfo {
        name: "globals",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "globals()",
        doc: "Return the dictionary containing the current scope's global variables.",
    },
    BuiltinInfo {
        name: "hasattr",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "hasattr(obj, name, /)",
        doc: "Return whether the object has an attribute with the given name.",
    },
    BuiltinInfo {
        name: "hash",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "hash(obj, /)",
        doc: "Return the hash value for the given object.",
    },
    BuiltinInfo {
        name: "help",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "help(request=None)",
        doc: "Invoke the built-in help system.",
    },
    BuiltinInfo {
        name: "hex",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "hex(number, /)",
        doc: "Return the hexadecimal representation of an integer.",
    },
    BuiltinInfo {
        name: "id",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "id(obj, /)",
        doc: "Return the identity of an object.",
    },
    BuiltinInfo {
        name: "input",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "input(prompt='')",
        doc: "Read a string from standard input.",
    },
    BuiltinInfo {
        name: "int",
        kind: CompletionItemKind::CLASS,
        detail: "builtin",
        signature: "class int(x=0, base=10)",
        doc: "Convert a number or string to an integer.",
    },
    BuiltinInfo {
        name: "isinstance",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "isinstance(obj, classinfo, /)",
        doc: "Return whether an object is an instance of a class or of a subclass thereof.",
    },
    BuiltinInfo {
        name: "issubclass",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "issubclass(cls, classinfo, /)",
        doc: "Return whether 'cls' is derived from another class or is the same class.",
    },
    BuiltinInfo {
        name: "iter",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "iter(object, sentinel=...)",
        doc: "Get an iterator from an object.",
    },
    BuiltinInfo {
        name: "len",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "len(obj, /)",
        doc: "Return the number of items in a container.",
    },
    BuiltinInfo {
        name: "list",
        kind: CompletionItemKind::CLASS,
        detail: "builtin",
        signature: "class list(iterable=())",
        doc: "Built-in mutable sequence.",
    },
    BuiltinInfo {
        name: "locals",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "locals()",
        doc: "Return a dictionary containing the current scope's local variables.",
    },
    BuiltinInfo {
        name: "map",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "map(func, *iterables)",
        doc: "Make an iterator that computes the function using arguments from each of the iterables.",
    },
    BuiltinInfo {
        name: "max",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "max(iterable, /, *, key=None, default=...)",
        doc: "Return the largest item in an iterable or the largest of two or more arguments.",
    },
    BuiltinInfo {
        name: "memoryview",
        kind: CompletionItemKind::CLASS,
        detail: "builtin",
        signature: "class memoryview(object)",
        doc: "Create a memoryview that references the given object.",
    },
    BuiltinInfo {
        name: "min",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "min(iterable, /, *, key=None, default=...)",
        doc: "Return the smallest item in an iterable or the smallest of two or more arguments.",
    },
    BuiltinInfo {
        name: "next",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "next(iterator, default=...)",
        doc: "Retrieve the next item from the iterator.",
    },
    BuiltinInfo {
        name: "object",
        kind: CompletionItemKind::CLASS,
        detail: "builtin",
        signature: "class object()",
        doc: "The base class of the class hierarchy.",
    },
    BuiltinInfo {
        name: "oct",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "oct(number, /)",
        doc: "Return the octal representation of an integer.",
    },
    BuiltinInfo {
        name: "open",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "open(file, mode='r', buffering=-1, encoding=None, errors=None, newline=None, closefd=True, opener=None)",
        doc: "Open file and return a stream.",
    },
    BuiltinInfo {
        name: "ord",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "ord(c, /)",
        doc: "Return the Unicode code point for a one-character string.",
    },
    BuiltinInfo {
        name: "pow",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "pow(base, exp, mod=None)",
        doc: "Equivalent to base**exp with 2 arguments or base**exp % mod with 3 arguments.",
    },
    BuiltinInfo {
        name: "print",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "print(*objects, sep=' ', end='\\n', file=None, flush=False)",
        doc: "Print objects to the text stream file, separated by sep and followed by end.",
    },
    BuiltinInfo {
        name: "property",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "property(fget=None, fset=None, fdel=None, doc=None)",
        doc: "Return a property attribute.",
    },
    BuiltinInfo {
        name: "range",
        kind: CompletionItemKind::CLASS,
        detail: "builtin",
        signature: "class range(stop)\nclass range(start, stop, step=1)",
        doc: "Return an immutable sequence of numbers.",
    },
    BuiltinInfo {
        name: "repr",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "repr(obj, /)",
        doc: "Return a string containing a printable representation of an object.",
    },
    BuiltinInfo {
        name: "reversed",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "reversed(sequence, /)",
        doc: "Return a reverse iterator over the values of the given sequence.",
    },
    BuiltinInfo {
        name: "round",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "round(number, ndigits=None)",
        doc: "Round a number to a given precision in decimal digits.",
    },
    BuiltinInfo {
        name: "set",
        kind: CompletionItemKind::CLASS,
        detail: "builtin",
        signature: "class set(iterable=())",
        doc: "Build an unordered collection of unique elements.",
    },
    BuiltinInfo {
        name: "setattr",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "setattr(obj, name, value, /)",
        doc: "Sets the named attribute on the given object to the specified value.",
    },
    BuiltinInfo {
        name: "slice",
        kind: CompletionItemKind::CLASS,
        detail: "builtin",
        signature: "class slice(stop)\nclass slice(start, stop, step=None)",
        doc: "Create a slice object.",
    },
    BuiltinInfo {
        name: "sorted",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "sorted(iterable, /, *, key=None, reverse=False)",
        doc: "Return a new list containing all items from the iterable in ascending order.",
    },
    BuiltinInfo {
        name: "staticmethod",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "staticmethod(function)",
        doc: "Convert a function to be a static method.",
    },
    BuiltinInfo {
        name: "str",
        kind: CompletionItemKind::CLASS,
        detail: "builtin",
        signature: "class str(object='')",
        doc: "Return a string version of object.",
    },
    BuiltinInfo {
        name: "sum",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "sum(iterable, /, start=0)",
        doc: "Return the sum of a 'start' value (default: 0) plus an iterable of numbers.",
    },
    BuiltinInfo {
        name: "super",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "super(type=None, object_or_type=None)",
        doc: "Return a proxy object that delegates method calls to a parent or sibling class.",
    },
    BuiltinInfo {
        name: "tuple",
        kind: CompletionItemKind::CLASS,
        detail: "builtin",
        signature: "class tuple(iterable=())",
        doc: "Built-in immutable sequence.",
    },
    BuiltinInfo {
        name: "type",
        kind: CompletionItemKind::CLASS,
        detail: "builtin",
        signature: "class type(object)\nclass type(name, bases, dict)",
        doc: "With one argument, return the type of an object. With three arguments, return a new type object.",
    },
    BuiltinInfo {
        name: "vars",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "vars(object=None)",
        doc: "Return the __dict__ attribute for a module, class, instance, or any other object with a __dict__ attribute.",
    },
    BuiltinInfo {
        name: "zip",
        kind: CompletionItemKind::FUNCTION,
        detail: "builtin",
        signature: "zip(*iterables, strict=False)",
        doc: "Iterate over several iterables in parallel, producing tuples with an item from each one.",
    },
    // constants
    BuiltinInfo {
        name: "True",
        kind: CompletionItemKind::CONSTANT,
        detail: "builtin",
        signature: "True",
        doc: "Boolean true value.",
    },
    BuiltinInfo {
        name: "False",
        kind: CompletionItemKind::CONSTANT,
        detail: "builtin",
        signature: "False",
        doc: "Boolean false value.",
    },
    BuiltinInfo {
        name: "None",
        kind: CompletionItemKind::CONSTANT,
        detail: "builtin",
        signature: "None",
        doc: "Represents the absence of a value.",
    },
    BuiltinInfo {
        name: "Ellipsis",
        kind: CompletionItemKind::CONSTANT,
        detail: "builtin",
        signature: "Ellipsis",
        doc: "The same as the literal `...`.",
    },
    BuiltinInfo {
        name: "__name__",
        kind: CompletionItemKind::CONSTANT,
        detail: "builtin",
        signature: "__name__: str",
        doc: "The name of the current module.",
    },
    BuiltinInfo {
        name: "__doc__",
        kind: CompletionItemKind::CONSTANT,
        detail: "builtin",
        signature: "__doc__: str | None",
        doc: "The module's documentation string.",
    },
    BuiltinInfo {
        name: "__file__",
        kind: CompletionItemKind::CONSTANT,
        detail: "builtin",
        signature: "__file__: str",
        doc: "The pathname of the file from which the module was loaded.",
    },
    // common exceptions
    BuiltinInfo {
        name: "Exception",
        kind: CompletionItemKind::CLASS,
        detail: "builtin",
        signature: "class Exception(*args)",
        doc: "Common base class for all non-exit exceptions.",
    },
    BuiltinInfo {
        name: "BaseException",
        kind: CompletionItemKind::CLASS,
        detail: "builtin",
        signature: "class BaseException(*args)",
        doc: "Common base class for all exceptions.",
    },
    BuiltinInfo {
        name: "TypeError",
        kind: CompletionItemKind::CLASS,
        detail: "builtin",
        signature: "class TypeError(*args)",
        doc: "Inappropriate argument type.",
    },
    BuiltinInfo {
        name: "ValueError",
        kind: CompletionItemKind::CLASS,
        detail: "builtin",
        signature: "class ValueError(*args)",
        doc: "Inappropriate argument value (of correct type).",
    },
    BuiltinInfo {
        name: "KeyError",
        kind: CompletionItemKind::CLASS,
        detail: "builtin",
        signature: "class KeyError(*args)",
        doc: "Mapping key not found.",
    },
    BuiltinInfo {
        name: "IndexError",
        kind: CompletionItemKind::CLASS,
        detail: "builtin",
        signature: "class IndexError(*args)",
        doc: "Sequence index out of range.",
    },
    BuiltinInfo {
        name: "AttributeError",
        kind: CompletionItemKind::CLASS,
        detail: "builtin",
        signature: "class AttributeError(*args)",
        doc: "Attribute not found.",
    },
    BuiltinInfo {
        name: "ImportError",
        kind: CompletionItemKind::CLASS,
        detail: "builtin",
        signature: "class ImportError(*args)",
        doc: "Import can't find module, or can't find name in module.",
    },
    BuiltinInfo {
        name: "RuntimeError",
        kind: CompletionItemKind::CLASS,
        detail: "builtin",
        signature: "class RuntimeError(*args)",
        doc: "Unspecified run-time error.",
    },
    BuiltinInfo {
        name: "StopIteration",
        kind: CompletionItemKind::CLASS,
        detail: "builtin",
        signature: "class StopIteration(*args)",
        doc: "Signal the end from iterator.__next__().",
    },
    BuiltinInfo {
        name: "OSError",
        kind: CompletionItemKind::CLASS,
        detail: "builtin",
        signature: "class OSError(*args)",
        doc: "Base class for I/O related errors.",
    },
    BuiltinInfo {
        name: "IOError",
        kind: CompletionItemKind::CLASS,
        detail: "builtin",
        signature: "class IOError(*args)",
        doc: "Alias for OSError.",
    },
    BuiltinInfo {
        name: "FileNotFoundError",
        kind: CompletionItemKind::CLASS,
        detail: "builtin",
        signature: "class FileNotFoundError(*args)",
        doc: "File not found.",
    },
    BuiltinInfo {
        name: "NotImplementedError",
        kind: CompletionItemKind::CLASS,
        detail: "builtin",
        signature: "class NotImplementedError(*args)",
        doc: "Method or function hasn't been implemented yet.",
    },
    BuiltinInfo {
        name: "AssertionError",
        kind: CompletionItemKind::CLASS,
        detail: "builtin",
        signature: "class AssertionError(*args)",
        doc: "Assertion failed.",
    },
];
