[package]
name = "sneklsp_db"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
sneklsp_text.workspace = true
sneklsp_parser.workspace = true
sneklsp_lexer.workspace = true
sneklsp_ast.workspace = true
sneklsp_index.workspace = true
sneklsp_vfs.workspace = true

salsa.workspace = true
tracing.workspace = true

[lints]
workspace = true

